### ISSUE TITLE
Fix error in web-client configuration

### ISSUE THREAD

**Issue by tcompa** [exactlab/fractal-containers#3]
```python traceback
INFO:     172.23.0.4:40864 - "GET /auth/whoami HTTP/1.1" 401 Unauthorized
INFO:     172.23.0.4:40864 - "GET /api/alive/ HTTP/1.1" 200 OK
CRITICAL:root:I AM IN current_user_dependency
CRITICAL:root:args=()
CRITICAL:root:kwargs={'user_manager': <fractal_server.app.security.UserManager object at 0x7f332846e050>, 'bearerjwt': None, 'strategy_bearerjwt': <fastapi_users.authentication.strategy.jwt.JWTStrategy object at 0x7f3328456990>, 'cookiejwt': None, 'strategy_cookiejwt': <fastapi_users.authentication.strategy.jwt.JWTStrategy object at 0x7f3328457210>}
CRITICAL:root:I AM IN _authenticate
CRITICAL:root:enabled_backends=[<fastapi_users.authentication.backend.AuthenticationBackend object at 0x7f332a43a650>, <fastapi_users.authentication.backend.AuthenticationBackend object at 0x7f332b331790>]
CRITICAL:root:backend=<fastapi_users.authentication.backend.AuthenticationBackend object at 0x7f332a43a650>
CRITICAL:root:backend is enabled
CRITICAL:root:name_to_variable_name(backend.name)='bearerjwt'
CRITICAL:root:token_key='bearerjwt'
CRITICAL:root:(token_key in kwargs.keys())=True
CRITICAL:root:kwargs.get(token_key, 111)=None
CRITICAL:root:token=None
CRITICAL:root:backend=<fastapi_users.authentication.backend.AuthenticationBackend object at 0x7f332b331790>
CRITICAL:root:backend is enabled
CRITICAL:root:name_to_variable_name(backend.name)='cookiejwt'
CRITICAL:root:token_key='cookiejwt'
CRITICAL:root:(token_key in kwargs.keys())=True
CRITICAL:root:kwargs.get(token_key, 111)=None
CRITICAL:root:token=None
CRITICAL:root:BEFORE if-user
CRITICAL:root:user=None
CRITICAL:root:Now re-raising something..
CRITICAL:root:e=HTTPException(status_code=401, detail='Unauthorized')
```

This is tested with (roughly) 4e283eddf462501579fee4bd7d2d4e164490f6bf, and triggered by trying to log-in.

**Comment by tcompa** [comment]
Some more logs.

I modified the `src/lib/server/api/v1/auth_api.js` `whoami` function as in https://www.reddit.com/r/sveltejs/comments/r8jog9/server_requests_with_cookies_solved/how58j6, adding
```
headers: {
            cookie: request.headers.cookie
        }
```
to the `fetch` call. See
![Screenshot from 2023-09-01 14-06-46](https://github.com/exactlab/fractal-containers/assets/3862206/d3dffe3f-5545-4289-95ac-e9749fe8b61e)

Then, in `src/routes/+layout.server.js`, I modified the call to `whoami` to also include `request`, which I also include as an argument of the `load` function.

The logs I got are
![Screenshot from 2023-09-01 14-08-13](https://github.com/exactlab/fractal-containers/assets/3862206/091a6213-c30c-43a2-8795-f249defe6d7d)

This shows that the `whoami` function "knows" about the correct cookie.

**Comment by aangelone2** [comment]
Solved in `01ff4f` by adapting code to pull web client from upstream branch `274-fix-cookie-issue`, where issue with cookie blocking has been solved.

**Comment by aangelone2** [comment]
Solved in `01ff4f` by adapting code to pull web client from upstream branch `274-fix-cookie-issue`, where issue with cookie blocking has been solved.
