### ISSUE TITLE
`/tmp/fractal_test` is not visible from host machine

### ISSUE THREAD

**Issue by tcompa** [exactlab/fractal-containers#4]
We set `FRACTAL_TASKS_DIR=/tmp/fractal_test/tasks` in `server.env`, and it is parsed correctly.
I triggered a task-package collection from the web client, and the logs show it went through.

Now I have:
```
# From fractal-server:
root@c9002d114684:/app# ls /tmp/fractal_test/tasks/.fractal/
fractal-tasks-core0.10.1

# From host machine:
$ ls /tmp/fractal_test
ls: cannot access '/tmp/fractal_test': No such file or directory
```

**Comment by aangelone2** [comment]
Closed in `95f60e2`
